##
## Config file for default TES fit in mutau channel
## contact: saskia.falke@cern.ch
##

# NOTE: In general, the main information (channel, baselineCuts, etc.) should be given.
#       More specific sub-options (like weight replacement for systematic uncertainties) are optional
#       These are used for the TES fit and are not needed for plotting only


# Typically, each channel will have its own config file; combination can be done at datacard level
channel: mutau_inclusive
# Tag can be used to differentiate between scenarios
tag: ""

baselineCuts: "q_1*q_2<0 && iso_1<0.15 && !lepton_vetoes_notau && metfilter" # && rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4  && rawPNetVSmu_2>=0.99" # && !idDecayModeNewDMs_2" 
# These regions will be defined when creating inputs or making plots
# At this point, they do not need to be exclusive; 
# PLEASE NOTE:
#     - which regions are included in the fit will be defined in obervables section --> adjust when changing regions
#     - additional cross section scale factors applied to some processes need to be given in these regions to be considered --> adjust in scaleFactors section

regions:
   signalRegion: 
      definition: "mt_1<40"
      title: "signal region"
   hps_region:
      definition: "mt_1<40 && idDecayModeNewDMs_2"
      title: "HPS #tau 's"
   deepTau_region:
      definition: "mt_1<40 && idDecayModeNewDMs_2 && idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSe_2>=2 && idDeepTau2018v2p5VSmu_2>=4 && (dm_2 == 0 || dm_2 == 1 || dm_2 == 10 || dm_2 == 11 )"
      title: "DeepTau region"
   pnet_hps_region:
      definition: "mt_1<40 && rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4  && rawPNetVSmu_2>=0.99 && (decayModePNet_2 == 0 || decayModePNet_2 == 1 || decayModePNet_2 == 2 || decayModePNet_2 == 10 || decayModePNet_2 == 11) && ( (idDecayModeNewDMs_2 && idDeepTau2018v2p5VSmu_2>=4) || !idDecayModeNewDMs_2)"
      title: "HPS conditions"
   # DM0: 
   #    definition: "mt_1<40 && dm_2==0"
   #    title: "h^{#pm}"
   # DM1: 
   #    definition: "mt_1<40 && dm_2==1"
   #    title: "h^{#pm}#pi^{0}"
   # DM10: 
   #    definition: "mt_1<40 && dm_2==10"
   #    title: "h^{#pm}h^{#mp}h^{#pm}"
   # DM11: 
   #    definition: "mt_1<40 && dm_2==11"
   #    title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}"
   # PNetDM0: 
   #    definition: "mt_1<40 && decayModePNet_2==0"
   #    title: "PNetDM 0"
   # PNetDM1: 
   #    definition: "mt_1<40 && decayModePNet_2==1"
   #    title: "PNetDM 1"
   # PNetDM2: 
   #    definition: "mt_1<40 && decayModePNet_2==2"
   #    title: "PNetDM 2"
   # PNetDM10: 
   #    definition: "mt_1<40 && decayModePNet_2==10"
   #    title: "PNetDM 10"
   # PNetDM11: 
   #    definition: "mt_1<40 && decayModePNet_2==11"
   #    title: "PNetDM 11" #"pnetdms h^{#pm}h^{#mp}h^{#pm}#pi^{0}"
   # PNetNoDM2:
   #    definition: "mt_1<40 && decayModePNet_2!=2"
   #    title: "pnetdm!=2"
   # idDeepTauVSmu:
   #    definition: "mt_1<40 && idDeepTau2018v2p5VSmu_2>=4"
   #    title: "VSmu: Tight_{DeepTau}"
   # HPSorPNet:
   #    definition: "mt_1 < 40 && ( (idDecayModeNewDMs_2 && idDeepTau2018v2p5VSmu_2>=4) || !idDecayModeNewDMs_2)"
   #    title: "HPS conditions"
   # PNetDM0HighEta:
   #    definition: "mt_1<40 && decayModePNet_2==0 && abs(eta_2) > 1.7"
   #    title: "DM_{PNet} abs(#eta) > 1.7"
   # PNetDM0LowEta:
   #    definition: "mt_1<40 && decayModePNet_2==0 && abs(eta_2) < 1.7"
   #    title: "DM_{PNet} abs(#eta) < 1.7"
   # genDM0: 
   #    definition: "mt_1<40 && gendm_2==0"
   #    title: "genDM 0"
   # genDM1: 
   #    definition: "mt_1<40 && gendm_2==1"
   #    title: "genDM 1"
   # genDM10: 
   #    definition: "mt_1<40 && gendm_2==10"
   #    title: "genDM 10"
   # genDM11: 
   #    definition: "mt_1<40 && gendm_2==11"
   #    title: "genDM 11"
# # Jet Medium, Electron VLoose, Muon Tight
#    VSjetMedVSeVL:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.747"
#       title: "M_{VSjet}, VL_{VSe}, 0.99_{VSmu}"
#    VSjetMedVSeVLDM0:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.747 && dm_2==0"
#       title: "M_{VSjet}, VL_{VSe}, 0.99_{VSmu}, h^{#pm}"
#    VSjetMedVSeVLDM1:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.747 && dm_2==1"
#       title: "M_{VSjet}, VL_{VSe}, 0.99_{VSmu}, h^{#pm}#pi^{0}"
#    VSjetMedVSeVLDM10:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.747 && dm_2==10"
#       title: "M_{VSjet}, VL_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}"
#    VSjetMedVSeVLDM11:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.747 && dm_2==11"
#       title: "M_{VSjet}, VL_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}#pi^{0}"

# # Jet Medium, Electron Loose, Muon Tight
#    VSjetMedVSeL:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.956"
#       title: "M_{VSjet}, L_{VSe}, 0.99_{VSmu}"
#    VSjetMedVSeLDM0:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.956 && dm_2==0"
#       title: "M_{VSjet}, L_{VSe}, 0.99_{VSmu}, h^{#pm}"
#    VSjetMedVSeLDM1:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.956 && dm_2==1"
#       title: "M_{VSjet}, L_{VSe}, 0.99_{VSmu}, h^{#pm}#pi^{0}"
#    VSjetMedVSeLDM10:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.956 && dm_2==10"
#       title: "M_{VSjet}, L_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}"
#    VSjetMedVSeLDM11:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.956 && dm_2==11"
#       title: "M_{VSjet}, L_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}#pi^{0}"

# # Jet Medium, Electron Medium, Muon Tight
#    VSjetMedVSeMed:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.983"
#       title: "M_{VSjet}, M_{VSe}, 0.99_{VSmu}"
#    VSjetMedVSeMedDM0:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.983 && dm_2==0"
#       title: "M_{VSjet}, M_{VSe}, 0.99_{VSmu}, h^{#pm}"
#    VSjetMedVSeMedDM1:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.983 && dm_2==1"
#       title: "M_{VSjet}, M_{VSe}, 0.99_{VSmu}, h^{#pm}#pi^{0}"
#    VSjetMedVSeMedDM10:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.983 && dm_2==10"
#       title: "M_{VSjet}, M_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}"
#    VSjetMedVSeMedDM11:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.983 && dm_2==11"
#       title: "M_{VSjet}, M_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}#pi^{0}"

# # Jet Medium, Electron Tight, Muon Tight
#    VSjetMedVSeT:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.992"
#       title: "M_{VSjet}, T_{VSe}, 0.99_{VSmu}"
#    VSjetMedVSeTDM0:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.992 && dm_2==0"
#       title: "M_{VSjet}, T_{VSe}, 0.99_{VSmu}, h^{#pm}"
#    VSjetMedVSeTDM1:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.992 && dm_2==1"
#       title: "M_{VSjet}, T_{VSe}, 0.99_{VSmu}, h^{#pm}#pi^{0}"
#    VSjetMedVSeTDM10:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.992 && dm_2==10"
#       title: "M_{VSjet}, T_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}"
#    VSjetMedVSeTDM11:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.992 && dm_2==11"
#       title: "M_{VSjet}, T_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}#pi^{0}"

# # Jet Medium, Electron VTight, Muon Tight
#    VSjetMedVSeVT:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.996"
#       title: "M_{VSjet}, VT_{VSe}, 0.99_{VSmu}"
#    VSjetMedVSeVTDM0:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.996 && dm_2==0"
#       title: "M_{VSjet}, VT_{VSe}, 0.99_{VSmu}, h^{#pm}"
#    VSjetMedVSeVTDM1:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.996 && dm_2==1"
#       title: "M_{VSjet}, VT_{VSe}, 0.99_{VSmu}, h^{#pm}#pi^{0}"
#    VSjetMedVSeVTDM10:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.996 && dm_2==10"
#       title: "M_{VSjet}, VT_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}"
#    VSjetMedVSeVTDM11:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.996 && dm_2==11"
#       title: "M_{VSjet}, VT_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}#pi^{0}"

# # Jet Medium, Electron VVTight, Muon Tight
#    VSjetMedVSeVVT:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.998"
#       title: "M_{VSjet}, VVT_{VSe}, 0.99_{VSmu}"
#    VSjetMedVSeVVTDM0:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.998 && dm_2==0"
#       title: "M_{VSjet}, VVT_{VSe}, 0.99_{VSmu}, h^{#pm}"
#    VSjetMedVSeVVTDM1:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.998 && dm_2==1"
#       title: "M_{VSjet}, VVT_{VSe}, 0.99_{VSmu}, h^{#pm}#pi^{0}"
#    VSjetMedVSeVVTDM10:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.998 && dm_2==10"
#       title: "M_{VSjet}, VVT_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}"
#    VSjetMedVSeVVTDM11:
#       definition: "mt_1<40 && rawPNetVSe_2>=0.998 && dm_2==11"
#       title: "M_{VSjet}, VVT_{VSe}, 0.99_{VSmu}, h^{#pm}h^{#mp}h^{#pm}#pi^{0}"



    # VSjetTedVSeVVL:
    #     definition: "mt_1<40 && rawPNetVSjet_2>=0.937"
    #     title: "T_{VSjet}, VVL_{VSe}, 0.98_{VSmu}"
    # VSjetTedVSeVVLDM0:
    #     definition: "mt_1<40 && rawPNetVSjet_2>=0.937 && dm_2==0"
    #     title: "T_{VSjet}, VVL_{VSe}, 0.98_{VSmu}, h^{#pm}"
    # VSjetTedVSeVVLDM1:
    #     definition: "mt_1<40 && rawPNetVSjet_2>=0.937 && dm_2==1"
    #     title: "T_{VSjet}, VVL_{VSe}, 0.98_{VSmu}, h^{#pm}#pi^{0}"
    # VSjetTedVSeVVLDM10:
    #     definition: "mt_1<40 && rawPNetVSjet_2>=0.937 && dm_2==10"
    #     title: "T_{VSjet}, VVL_{VSe}, 0.98_{VSmu}, h^{#pm}h^{#mp}h^{#pm}"
    # VSjetTedVSeVVLDM11:
    #     definition: "mt_1<40 && rawPNetVSjet_2>=0.937 && dm_2==11"
    #     title: "T_{VSjet}, VVL_{VSe}, 0.98_{VSmu}, h^{#pm}h^{#mp}h^{#pm}#pi^{0}"

    # VSjetTedVSeT:
    #     definition: "mt_1<40 && rawPNetVSjet_2>=0.937 && rawPNetVSe_2>=0.992"
    #     title: "T_{VSjet}, T_{VSe}, 0.98_{VSmu}"
    # VSjetTedVSeTDM0:
    #     definition: "mt_1<40 && rawPNetVSjet_2>=0.937 && rawPNetVSe_2>=0.992 && dm_2==0"
    #     title: "T_{VSjet}, T_{VSe}, 0.98_{VSmu}, h^{#pm}"
    # VSjetTedVSeTDM1:
    #     definition: "mt_1<40 && rawPNetVSjet_2>=0.937 && rawPNetVSe_2>=0.992 && dm_2==1"
    #     title: "T_{VSjet}, T_{VSe}, 0.98_{VSmu}, h^{#pm}#pi^{0}"
    # VSjetTedVSeTDM10:
    #     definition: "mt_1<40 && rawPNetVSjet_2>=0.937 && rawPNetVSe_2>=0.992 && dm_2==10"
    #     title: "T_{VSjet}, T_{VSe}, 0.98_{VSmu}, h^{#pm}h^{#mp}h^{#pm}"
    # VSjetTedVSeTDM11:
    #     definition: "mt_1<40 && rawPNetVSjet_2>=0.937 && rawPNetVSe_2>=0.992 && dm_2==11"
    #     title: "T_{VSjet}, T_{VSe}, 0.98_{VSmu}, h^{#pm}h^{#mp}h^{#pm}#pi^{0}"

    # baselineDeepTau:
    #     definition: "idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSe_2>=2 && idDeepTau2018v2p5VSmu_2>=4"
    #     title: "DeepT: M_{VSjet}, VVL_{VSe}, 0.995_{VSmu}"
    # baselineDeepTauSR:
    #     definition: "idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSe_2>=2 && idDeepTau2018v2p5VSmu_2>=4 && mt_1<40"
    #     title: "DeepT: M_{VSjet}, VVL_{VSe}, 0.995_{VSmu}, SR"
    # baselineDeepTauDM0:
    #     definition: "idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSe_2>=2 && idDeepTau2018v2p5VSmu_2>=4 && mt_1<40 && dm_2==0"
    #     title: "DeepT: M_{VSjet}, VVL_{VSe}, 0.995_{VSmu}, h^{#pm}"
    # baselineDeepTauDM1:
    #     definition: "idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSe_2>=2 && idDeepTau2018v2p5VSmu_2>=4 && mt_1<40 && dm_2==1"
    #     title: "DeepT: M_{VSjet}, VVL_{VSe}, 0.995_{VSmu}, h^{#pm}#pi^{0}"
    # baselineDeepTauDM10:
    #     definition: "idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSe_2>=2 && idDeepTau2018v2p5VSmu_2>=4 && mt_1<40 && dm_2==10"
    #     title: "DeepT: M_{VSjet}, VVL_{VSe}, 0.995_{VSmu}, h^{#pm}h^{#mp}h^{#pm}"
    # baselineDeepTauDM11:
    #     definition: "idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSe_2>=2 && idDeepTau2018v2p5VSmu_2>=4 && mt_1<40 && dm_2==11"
    #     title: "DeepT: M_{VSjet}, VVL_{VSe}, 0.995_{VSmu}, h^{#pm}h^{#mp}h^{#pm}#pi^{0}"
    # baselinePNet:
    #     definition: "rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4  && rawPNetVSmu_2>=0.9"
    #     title: "M_{VSjet}, VVL_{VSe}, 0.98_{VSmu}"
    # baselinePNetSR:
    #     definition: "rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4  && rawPNetVSmu_2>=0.9 && mt_1<40"
    #     title: "M_{VSjet}, VVL_{VSe}, 0.98_{VSmu}, SR"
    # baselinePNetDM0:
    #     definition: "rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4  && rawPNetVSmu_2>=0.9 && mt_1<40 && dm_2==0"
    #     title: "M_{VSjet}, VVL_{VSe}, 0.98_{VSmu}, h^{#pm}"
    # baselinePNetDM1:
    #     definition: "rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4  && rawPNetVSmu_2>=0.9 && mt_1<40 && dm_2==1"
    #     title: "M_{VSjet}, VVL_{VSe}, 0.98_{VSmu}, h^{#pm}#pi^{0}"
    # baselinePNetDM10:
    #     definition: "rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4  && rawPNetVSmu_2>=0.9 && mt_1<40 && dm_2==10"
    #     title: "M_{VSjet}, VVL_{VSe}, 0.98_{VSmu}, h^{#pm}h^{#mp}h^{#pm}"
    # baselinePNetDM11:
    #     definition: "rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4  && rawPNetVSmu_2>=0.9 && mt_1<40 && dm_2==11"
    #     title: "M_{VSjet}, VVL_{VSe}, 0.98_{VSmu}, h^{#pm}h^{#mp}h^{#pm}#pi^{0}"
    # jetTeVVL:
    #     definition: "rawPNetVSjet_2>=0.937"
    #     title: "VSjet: T, VSe: VVL"
    # jetVTeVVL:
    #     definition: "rawPNetVSjet_2>=0.968"
    #     title: "VSjet: VT, VSe: VVL"
    # jetVVTeVVL:
    #     definition: "rawPNetVSjet_2>=0.982"
    #     title: "VSjet: VVT, VSe: VVL"
    # jetTeVL:
    #     definition: "rawPNetVSjet_2>=0.937 && rawPNetVSe_2>=0.747"
    #     title: "VSjet: T, VSe: VL"
    # jetTeL:
    #     definition: "rawPNetVSjet_2>=0.937 && rawPNetVSe_2>=0.956"
    #     title: "VSjet: T, VSe: L"
    # jetTeM:
    #     definition: "rawPNetVSjet_2>=0.937 && rawPNetVSe_2>=0.983"
    #     title: "VSjet: T, VSe: M"
    #zttregion:
    #    definition: "mt_1<60 && dzeta>-25 && abs(deta_ll)<1.5"
    #    title: "mt<60 GeV, dzeta>-25 GeV, |deta|<1.5:"
    #0b:
    #    definition: "nbtag==0"
    #    weight: "btagweight"
    #geq1b:
    #    definition: "nbtag>=1"
    #    title: "#geq1b"
    #    weight: "btagweight"