##
## Config file for default TES fit in mutau channel
## contact: saskia.falke@cern.ch
##

# NOTE: In general, the main information (channel, baselineCuts, etc.) should be given.
#       More specific sub-options (like weight replacement for systematic uncertainties) are optional
#       These are not needed for plotting only


channel: etau

baselineCuts: "q_1*q_2<0 && iso_1<0.10 && mvaFall17noIso_WP90_1 && idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSmu_2>=4 && !lepton_vetoes_notau && metfilter" #&& idDeepTau2018v2p5VSe_2>=6"
regions:
    tightVsele_barrel:
       definition: "idDeepTau2018v2p5VSe_2>=6 && mt_1<60 && abs(eta_2) < 1.46"
       title: "Tight pass"
   #  tightForSFs:
   #     definition: "idDeepTau2018v2p5VSe_2>=6 && mt_1<30 && m_vis < 80 && m_vis > 40"
   #     title: "tight VSele for SF"
   #  VVLVsele:
   #     definition: "idDeepTau2018v2p5VSe_2>=2  && mt_1<60"
   #     title: "VVLoose VSele"
    VVLVsele_endcap:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) > 1.56 && abs(eta_2) < 2.5 && mt_1<60"
       title: "VVLoose pass"
    VVLVsele_barrel_0:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) < 1.46  && mt_1<60 && dm_2 ==0 "
       title: "VVLoose VSele barrel no pt cut DM0"
    VVLVsele_barrel_1:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) < 1.46  && mt_1<60 && dm_2 ==1 "
       title: "VVLoose VSele barrel no pt cut DM1"
    VVLVsele_barrel_10:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) < 1.46  && mt_1<60 && dm_2 ==10 "
       title: "VVLoose VSele barrel no pt cut DM10"
    VVLVsele_barrel_11:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) < 1.46  && mt_1<60 && dm_2 ==11 "
       title: "VVLoose VSele barrel no pt cut DM11"
    VVLVsele_barrel_11_0to0p2:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) < 0.2  && mt_1<60 && dm_2 ==11"
       title: "VVLoose VSele barrel no pt cut DM11 0 < |eta| < 0.2"
    VVLVsele_barrel_11_0p2to0p5:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) > 0.2 && abs(eta_2) < 0.5 && mt_1<60 && dm_2 ==11"
       title: "VVLoose VSele barrel no pt cut DM11 0.2 < |eta| < 0.5"
    VVLVsele_barrel_11_0p5to0p8:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) > 0.5 && abs(eta_2) < 0.8 && mt_1<60 && dm_2 ==11"
       title: "VVLoose VSele barrel no pt cut DM11 0.5 < |eta| < 0.8"
    VVLVsele_barrel_11_0p8to1p1:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) > 0.8 && abs(eta_2) < 1.1 && mt_1<60 && dm_2 ==11"
       title: "VVLoose VSele barrel no pt cut DM11 0.8 < |eta| < 1.1"
    VVLVsele_barrel_11_1p1to1p4:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) > 1.1 && abs(eta_2) < 1.4 && mt_1<60 && dm_2 ==11"
       title: "VVLoose VSele barrel no pt cut DM11 1.1 < |eta| < 1.4"
    VVLVsele_barrel_11_1p4to1p8:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) > 1.4 && abs(eta_2) < 1.8 && mt_1<60 && dm_2 ==11"
       title: "VVLoose VSele barrel no pt cut DM11 1.4 < |eta| < 1.8"
    VVLVsele_barrel_11_1p8to2p5:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) > 1.8 && abs(eta_2) < 2.5 && mt_1<60 && dm_2 ==11"
       title: "VVLoose VSele barrel no pt cut DM11 1.8 < |eta| < 2.5"
    VVLVsele_barrel:
       definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) < 1.46  && mt_1<60"
       title: "VVLoose pass"
   #  VVLVsele_barrel_lowpt:
   #     definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) < 1.46  && mt_1<60 && pt_2 < 50"
   #     title: "VVLoose VSele barrel low pt"
   #  VVLVsele_barrel_highpt:
   #     definition: "idDeepTau2018v2p5VSe_2>=2 && abs(eta_2) < 1.46  && mt_1<60 && pt_2 > 50"
   #     title: "VVLoose VSele barrel high pt"
    tightVsele_endcap:
       definition: "idDeepTau2018v2p5VSe_2>=6 && mt_1<60 && abs(eta_2) > 1.56 && abs(eta_2) < 2.5"
       title: "Tight pass"
   #  failVsele:
   #     definition: "idDeepTau2018v2p5VSe_2<2 && mt_1<60"
   #     title: "fail VSele"
    failVsele_endcap:
       definition: "idDeepTau2018v2p5VSe_2<6 && abs(eta_2) > 1.56 && abs(eta_2) < 2.5 && mt_1<60"
       title: "Tight fail"
    failVsele_barrel:
       definition: "idDeepTau2018v2p5VSe_2<6 && abs(eta_2) < 1.46 && mt_1<60"
       title: "Tight fail"
    failVVLVsele_endcap:
       definition: "idDeepTau2018v2p5VSe_2<2 && abs(eta_2) > 1.56 && abs(eta_2) < 2.5 && mt_1<60"
       title: "VVLoose fail"
    failVVLVsele_barrel:
       definition: "idDeepTau2018v2p5VSe_2<2 && abs(eta_2) < 1.46 && mt_1<60"
       title: "VVLoose fail"
