##
## Config file for default TES fit in mutau channel
## contact: saskia.falke@cern.ch
##

# NOTE: In general, the main information (channel, baselineCuts, etc.) should be given.
#       More specific sub-options (like weight replacement for systematic uncertainties) are optional
#       These are used for the TES fit and are not needed for plotting only


# Typically, each channel will have its own config file; combination can be done at datacard level
channel: mutau # _inclusive
# Tag can be used to differentiate between scenarios
tag: ""

baselineCuts: "q_1*q_2<0 && iso_1<0.15 && !lepton_vetoes_notau && metfilter" # && rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4  && rawPNetVSmu_2>=0.99" # && !idDecayModeNewDMs_2" 
# These regions will be defined when creating inputs or making plots
# At this point, they do not need to be exclusive; 
# PLEASE NOTE:
#     - which regions are included in the fit will be defined in obervables section --> adjust when changing regions
#     - additional cross section scale factors applied to some processes need to be given in these regions to be considered --> adjust in scaleFactors section

regions:
   signalRegion: 
      definition: "mt_1<65"
      title: "signal region"
   upart_region:
      definition: "mt_1<65 && rawUParTVSe_2>=0.104 && rawUParTVSjet_2>=0.514 && rawUParTVSmu_2>=0.888 && (decayModeUParT_2==0 || decayModeUParT_2==1 || decayModeUParT_2==2 || decayModeUParT_2==10 || decayModeUParT_2==11 )"
      title: "UParT"
   deepTau_region:
      definition: "mt_1<65 && idDecayModeNewDMs_2 && idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSe_2>=2 && idDeepTau2018v2p5VSmu_2>=4 && (dm_2==0 || dm_2==1 || dm_2==10 || dm_2==11 )"
      title: "DeepTau"
   pnet_region:
      definition: "mt_1<65 && rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4 && rawPNetVSmu_2>=0.99 && (decayModePNet_2==0 || decayModePNet_2==1 || decayModePNet_2==2 || decayModePNet_2==10 || decayModePNet_2==11)"
      title: "PNet"
   hps_region:
      definition: "mt_1<65 && idDecayModeNewDMs_2"
      title: "HPS #tau 's"
   pnet_hps_region:
      definition: "mt_1<65 && rawPNetVSjet_2>=0.881 && rawPNetVSe_2>=0.4  && rawPNetVSmu_2>=0.99 && (decayModePNet_2 == 0 || decayModePNet_2 == 1 || decayModePNet_2 == 2 || decayModePNet_2 == 10 || decayModePNet_2 == 11) && ( (idDecayModeNewDMs_2 && idDeepTau2018v2p5VSmu_2>=4) || !idDecayModeNewDMs_2)"
      title: "HPS conditions"