import ROOT
import os

ROOT.gROOT.SetBatch()
ROOT.gStyle.SetOptStat(0)

tau_fw_root = "/eos/user/a/atahmad/analysis/2024/Data/eff_plots/efficiencies_2024.root"
dps_root = "/eos/user/a/atahmad/analysis/2024/Data/botao/TurnOn_skimtuple_2024ALL_mutau_pt.root"
output_plot = "/eos/user/a/atahmad/analysis/2024/Data/eff_plots/eff_comparison_tau_trigger_2024_updated.png"

f_tau = ROOT.TFile.Open(tau_fw_root)
eff_pnet_tau = f_tau.Get("eff_pnet_2024")
eff_deep_tau = f_tau.Get("eff_deep_2024")
ratio_tau = eff_pnet_tau.Clone("ratio_tau")
ratio_tau.Divide(eff_deep_tau)

f_dps = ROOT.TFile.Open(dps_root)
total_pnet_dps = f_dps.Get("pnet_loose_mutau_Medium_plot_total")
pass_pnet_dps = f_dps.Get("pnet_loose_mutau_Medium_plot_passed")
total_deep_dps = f_dps.Get("deeptau_mutau_Medium_plot_total")
pass_deep_dps = f_dps.Get("deeptau_mutau_Medium_plot_passed")

eff_pnet_dps = pass_pnet_dps.Clone("eff_pnet_dps")
eff_pnet_dps.Divide(total_pnet_dps)
eff_deep_dps = pass_deep_dps.Clone("eff_deep_dps")
eff_deep_dps.Divide(total_deep_dps)

ratio_dps = eff_pnet_dps.Clone("ratio_dps")
ratio_dps.Divide(eff_deep_dps)

canvas = ROOT.TCanvas("canvas", "", 850, 850)
pad1 = ROOT.TPad("pad1", "pad1", 0.0, 0.30, 1.0, 1.0)
pad2 = ROOT.TPad("pad2", "pad2", 0.0, 0.0, 1.0, 0.27)
pad1.SetBottomMargin(0.013)
pad2.SetTopMargin(0.05)
pad2.SetBottomMargin(0.35)
pad1.SetLeftMargin(0.15)
pad2.SetLeftMargin(0.15)
pad1.SetRightMargin(0.25)
pad2.SetRightMargin(0.25)
pad1.SetGrid()
pad2.SetGrid()
pad1.Draw()
pad2.Draw()

pad1.cd()
frame1 = ROOT.TH1F("frame1", "", 100, 10, 150)
frame1.SetStats(0)
frame1.SetMinimum(0)
frame1.SetMaximum(1.1)
frame1.GetYaxis().SetTitle("L1+HLT Efficiency")
frame1.GetXaxis().SetLabelSize(0)
frame1.Draw()

eff_pnet_tau.SetLineColor(ROOT.kRed)
eff_pnet_tau.SetMarkerColor(ROOT.kRed)
eff_pnet_tau.SetMarkerStyle(20)
eff_pnet_tau.SetMarkerSize(0.9)
eff_pnet_tau.SetLineWidth(2)
eff_pnet_tau.Draw("EP SAME")

eff_deep_tau.SetLineColor(ROOT.kBlack)
eff_deep_tau.SetMarkerColor(ROOT.kBlack)
eff_deep_tau.SetMarkerStyle(20)
eff_deep_tau.SetMarkerSize(0.9)
eff_deep_tau.SetLineWidth(2)
eff_deep_tau.Draw("EP SAME")

eff_pnet_dps.SetLineColor(ROOT.kRed)
eff_pnet_dps.SetLineStyle(2)
eff_pnet_dps.SetMarkerColor(ROOT.kRed)
eff_pnet_dps.SetMarkerStyle(25)
eff_pnet_dps.SetMarkerSize(0.9)
eff_pnet_dps.SetLineWidth(2)
eff_pnet_dps.Draw("EP SAME")

eff_deep_dps.SetLineColor(ROOT.kBlack)
eff_deep_dps.SetLineStyle(2)
eff_deep_dps.SetMarkerColor(ROOT.kBlack)
eff_deep_dps.SetMarkerStyle(25)
eff_deep_dps.SetMarkerSize(0.9)
eff_deep_dps.SetLineWidth(2)
eff_deep_dps.Draw("EP SAME")

legend = ROOT.TLegend(0.77, 0.45, 0.97, 0.75)
legend.AddEntry(eff_pnet_tau, "TauFW PNet", "lp")
legend.AddEntry(eff_pnet_dps, "DPS PNet", "lp")
legend.AddEntry(eff_deep_tau, "TauFW DeepTau", "lp")
legend.AddEntry(eff_deep_dps, "DPS DeepTau", "lp")
legend.SetBorderSize(0)
legend.SetFillStyle(0)
legend.Draw()

latex = ROOT.TLatex()
latex.SetNDC()
latex.SetTextSize(0.045)
latex.DrawLatex(0.16, 0.91, "2024 Tau Trigger Efficiency Plots")

pad2.cd()
frame2 = ROOT.TH1F("frame2", "", 100, 10, 150)
frame2.SetStats(0)
frame2.SetMinimum(0.9)
frame2.SetMaximum(1.4)
frame2.GetYaxis().SetTitle("Ratio")
frame2.GetYaxis().SetTitleOffset(0.6)
frame2.GetYaxis().SetTitleSize(0.12)
frame2.GetYaxis().SetLabelSize(0.10)
frame2.GetXaxis().SetTitle("Offline p_{T}^{#tau} [GeV]")
frame2.GetXaxis().SetTitleSize(0.12)
frame2.GetXaxis().SetLabelSize(0.10)
frame2.GetYaxis().SetNdivisions(505)
frame2.Draw()

ratio_tau.SetMarkerColor(ROOT.kBlack)
ratio_tau.SetLineColor(ROOT.kBlack)
ratio_tau.SetLineWidth(2)
ratio_tau.SetMarkerStyle(20)
ratio_tau.SetMarkerSize(0.9)
ratio_tau.Draw("EP SAME")

ratio_dps.SetMarkerColor(ROOT.kRed)
ratio_dps.SetLineColor(ROOT.kRed)
ratio_dps.SetLineStyle(2)
ratio_dps.SetLineWidth(2)
ratio_dps.SetMarkerStyle(25)
ratio_dps.SetMarkerSize(0.9)
ratio_dps.Draw("EP SAME")

legend_ratio = ROOT.TLegend(0.77, 0.65, 0.97, 0.85)
legend_ratio.AddEntry(ratio_tau, "TauFW PNet/DeepTau", "lp")
legend_ratio.AddEntry(ratio_dps, "DPS PNet/DeepTau", "lp")
legend_ratio.SetBorderSize(0)
legend_ratio.SetFillStyle(0)
legend_ratio.Draw()

canvas.SaveAs(output_plot)
print("Saved:", output_plot)
