##
## Config file for default TES fit in mutau channel
## contact: saskia.falke@cern.ch
##

# NOTE: In general, the main information (channel, baselineCuts, etc.) should be given.
#       More specific sub-options (like weight replacement for systematic uncertainties) are optional


# Typically, each channel will have its own config file; combination can be done at datacard level

channel: mutau_v10_2p5

# Tag can be used to differentiate between scenarios

tag: "_mtlt50"

baselineCuts: "q_1*q_2<0 && iso_1<0.15 && idDecayModeNewDMs_2 && idDeepTau2018v2p5VSjet_2>=6 && idDeepTau2018v2p5VSe_2>=2 && idDeepTau2018v2p5VSmu_2>=4 && !lepton_vetoes_notau && metfilter"

# These regions will be defined when creating inputs or making plots
# At this point, they do not need to be exclusive; 
# PLEASE NOTE:
#     - which regions are included in the fit will be defined in obervables section --> adjust when changing regions
#     - additional cross section scale factors applied to some processes need to be given in these regions to be considered --> adjust in scaleFactors section

regions:
    DM0: 
        definition: "mt_1<50 && dm_2==0"
        title: "h^{#pm}"
    DM1: 
        definition: "mt_1<50 && dm_2==1"
        title: "h^{#pm}#pi^{0}"
    DM10: 
        definition: "mt_1<50 && dm_2==10"
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11: 
        definition: "mt_1<50 && dm_2==11"
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}"

# Optional argument to define the order of the bins in the summary plot
# Working without, but order might be random as disctionary is not sorted
plottingOrder: ["DM0", "DM1", "DM10", "DM11"]

# Observables to be fitted and plotted
# binning: as defined in TH1 (nbins, xmin, xmax)
# regions: (defined separately) to be included in the fit for this observable

observables:
    m_vis:
        binning: [8, 50, 106]
        title: "m_{vis}"
        extra:
            cut: "50<m_vis && m_vis<106"
        fitRegions: [DM0, DM1, DM10, DM11]
    #m_2:
    #    binning: [13, 0.3, 1.6]
    #    title: "m_{#tau_{h}}"
    #    extra:
    #        cut: "0.3<m_2 && m_2<1.6"
    #        ccut: 
    #            "dm_2==1(?!0)(?!1)": "0.35<m_2 && m_2<1.20"
    #            "dm_2==10":          "0.83<m_2 && m_2<1.43"
    #            "dm_2==11":          "0.93<m_2 && m_2<1.53"
    #        veto: "dm_2==0"
    #    fitRegions: [DM1, DM10, DM11]

# Assume that this code is meant to fit TES variations; more options could be added when adding other POIs

TESvariations:
    values: [0.970, 0.972, 0.974, 0.976, 0.978, 0.980, 0.982, 0.984, 0.986, 0.988, 0.990, 0.992, 0.994, 0.996, 0.998, 1.000, 1.002, 1.004, 1.006, 1.008, 1.010, 1.012, 1.014, 1.016, 1.018, 1.020, 1.022, 1.024, 1.026, 1.028, 1.030]
    processes: ["ZTT"]

# Should add bin-by-bin variations (stat. uncertainties) for signal and backgrounds?

fitSpecs:
    doBBB: doShapes
    signalBBB: True
    backgroundBBB: True


# Samples to be used and association to processes entering analysis
# Possibility to remove or add specific weights / SFs from global weight

samples:
    filename: "$PICODIR/$SAMPLE_$CHANNEL$TAG.root"
    join: ["VV","TT","ST"]
    split:
        DY: [ ["ZTT","genmatch_2==5"], ["ZL","genmatch_2>0 && genmatch_2<5"], ["ZJ","genmatch_2==0"] ]
        TT: [["TTT","genmatch_2==5"], ["TTL","genmatch_2>0 && genmatch_2<5"], ["TTJ","genmatch_2==0"] ]
        #ST: [("STT","genmatch_2==5"),("STJ","genmatch_2<5")]
    rename:
        WJ: "W"
    data: "data_obs"
    #removeSFs: ["idweight_2"]
    #addSFs: []


# Processes taken into account in analysis

processes: ["ZTT","ZL","ZJ","W","VV","ST","TTT","TTL","TTJ","QCD","data_obs"]

# Systematic uncertainties: can have effect shape or lnN (normalisation)

systematics:
    LTF:
        effect: "shape"
        processes: ["ZL", "TTL"]
        name: "shape_mTauFake_$BIN"
        title: "+/- 2% LTF shape"
        variations: ["Up", "Down"]
        sampleAppend: ["_LTFUp","_LTFDown"]
    JTF:
        effect: "shape"
        processes: ["ZJ", "TTJ", "W"]
        name: "shape_jTauFake_$BIN"
        title: "+/- 5% JTF"
        variations: ["Up", "Down"]
        sampleAppend: ["_JTFUp","_JTFDown"]
    shape_tid:
        effect: "shape"
        processes: ["ZTT", "TTT"]            
        name: "shape_tid"
        title: "TID shape syst"
        variations: ["Up", "Down"]
        nomWeight: "idweight_2"
        altWeights: ["idweightUp_2", "idweightDown_2"]
    shape_mTauFake:
        effect: "shape"
        processes: ["ZL", "TTL"]
        name: "shape_mTauFakeSF"
        title: "LTF rate syst"
        variations: ["Up", "Down"]
        nomWeight: "ltfweight_2"
        altWeights: ["ltfweightUp_2", "ltfweightDown_2"]
    shape_dy:
        effect: "shape"
        processes: ["ZTT", "ZL", "ZJ"]
        name: "shape_dy"
        title: "+/- 10% Zptweight"
        variations: ["Up", "Down"]
        nomWeight: "zptweight"
        altWeights: ["(zptweight+0.1*(zptweight-1))", "(zptweight-0.1*(zptweight-1))"]
    lumi:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ", "TTT", "TTL", "TTJ", "W", "ST", "VV"]
        scaleFactor: 1.025
    eff_m:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ", "TTT", "TTL", "TTJ", "W", "ST", "VV"]
        scaleFactor: 1.02
    xsec_dy:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ"]
        scaleFactor: 1.02
    xsec_tt:
        effect: "lnN"
        processes: ["TTT", "TTL", "TTJ"]
        scaleFactor: 1.06
    xsec_st:
        effect: "lnN"
        processes: ["ST"]
        scaleFactor: 1.05
    xsec_vv:
        effect: "lnN"
        processes: ["VV"]
        scaleFactor: 1.05
    norm_wj:
        effect: "lnN"
        processes: ["W"]
        scaleFactor: 1.08
    norm_qcd:
        effect: "lnN"
        processes: ["QCD"]
        scaleFactor: 1.10
    rate_jTauFake_$BIN:
        effect: "lnN"
        processes: ["W","QCD","ZJ","TTJ","STJ"]
        scaleFactor: 1.15

# Additional scale factors per year for specific processes (correction of xsec, reco SFs, etc.)

scaleFactors:
    WNFs:
        processes: ["W"]
        values:
            'UL2016_preVFP': { 'dm_2==0': 0.939,  'dm_2==1': 1.031,  'dm_2==10': 1.065,  'dm_2==11': 1.021  }
            'UL2016_postVFP': { 'dm_2==0': 0.919,  'dm_2==1': 0.972,  'dm_2==10': 1.112,  'dm_2==11': 1.074  }
            'UL2017': { 'dm_2==0': 0.971,  'dm_2==1': 0.995,  'dm_2==10': 1.109,  'dm_2==11': 1.075  }
            'UL2018': { 'dm_2==0': 1.007,  'dm_2==1': 0.968,  'dm_2==10': 1.079,  'dm_2==11': 1.044  }
